### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by humanumbrella** [afilini/bip174.org#21]
It looks like [bip174.org](https://bip174.org/) is unreachable

**Comment by afilini** [comment]
Yes, I'm currently doing some maintenance. It should be up tonight (EU time) or tomorrow, sorry for the inconvenience

**Comment by humanumbrella** [comment]
No worries, just sharing in case you didn't know. Cheers

**Comment by afilini** [comment]
Should be back up now, sorry once again!
