### ISSUE TITLE
Is the website bip174.org down?

### ISSUE THREAD

**Issue by DanGould** [afilini/bip174.org#33]
I've been looking for something like this awesome tool while developing PayJoins and PSBTv2 for a while but noticed the website is down. I saw [PSBT-toolkit](https://github.com/benthecarman/PSBT-Toolkit), but that needs to be compiled and run on my machine from scala .

Since this is all client side wasm couldn't it be hosted by github pages? That would be mega convenient and reliable based on my experience.

Edit: maybe it's server side rendered now, but I guess it could be all done in the browser.

**Comment by afilini** [comment]
It was a domain issue actually, so github pages wouldn't have made any difference in this case.

It should be fixed now, sorry for the inconvenience!

**Comment by DanGould** [comment]
Thank you :>
